
messages:
  authenticated: "§aAutenticazione avvenuta con successo."
  website: "https://craftopoly.it"
  discord: "https://discord.gg.ccccccc"
  premium_authenticated: "§aAutenticazione automatica avvenuta con successo."
  authentication_error: "§cErrore durante l'autenticazione."
  telegram_error: "§cErrore durante la generazione del tuo codice."
  telegram_already_connected: "§a§lTelegram\n\n §8▪ §7Il tuo Craftopoly ID è gia collegato ad un account telegram, se vuoi disconnetterlo esegui questo comando: §a/disconnect-telegram"
  telegram_connect: "§a§lTelegram\n\n §8▪ §7Per connettere il tuo Craftopoly ID al tuo account telegram avvia il bot §a@CraftopolyTicketsBOT e esegui questo comando: §a/connect {code}."
  already_authenticated: "§cSei già stato autenticato."
  authentication_failed: "§cPassword sbagliata, riprova."
  no_enough_permissions: "§cNon hai abbastanza permessi per eseguire questo comando"
  telegram_not_connected: " §cNon hai connesso alcun account telegram al tuo Craftopoly ID"
  telegram_disconnected: " §aHai disconnesso il tuo account telegram con successo"

  authenticate: "§a§lAutenticazione\n\n§8▪ §7Benvenuto §a{username}§7, Crea il tuo §aID§7 personale\n  §7per iniziare a giocare\n\n  §7⇨ /register <password>\n"
  login: "§a§lAutenticazione\n\n§8▪ §7Bentornato §a{username}§7, Inserisci la tua password\n  §7per iniziare a giocare\n\n  §7⇨ /login <password>\n"

settings:
  api_url: http://localhost:5000/api/v1