name: CO_Auth
version: '1.0-SNAPSHOT'
main: it.craftopoly.co_auth.CO_Auth
api-version: 1.20
commands:
  register:
    aliases: reg
  login:
    aliases: []
  connect-telegram:
    aliases: [ ]
  disconnect-telegram:
    aliases: [ ]
